
[[price]]
= Prices

All prices in the format are related to the article or service within this Pre-Award Catalogue. The following information on prices can be stated:

* Item price is net price including all discounts and charges but excluded Vat
* Item comparison unit price defining price for a certain quantity. Used for comparing prices for different articles with various quantities
* Conditional price related to a specific location or a certain quantity
* Campaign price
* Allowance Charge used to indicate and justify price discounts, allowances or charges

Be aware that no Gross prices can be sent in the format (price before discount and charges). All prices shall have Currency as an attribute. Currency shall be according to Code list.

Example of Prices and Allowances in the Pre-Award Catalogue:

[source]
.Item Price
----
include::../../../../rules/snippets/pre-award-catalogue/Prices.xml[tags=item-price]
----

[source]
.Comparison Price
----
include::../../../../rules/snippets/pre-award-catalogue/Prices.xml[tags=comparison-price]
----

[source]
.Conditional Price
----
include::../../../../rules/snippets/pre-award-catalogue/Prices.xml[tags=conditional-price]
----

[source]
.Allowance Charge
----
include::../../../../rules/snippets/pre-award-catalogue/Prices.xml[tags=allowance-charge]
----