sudo: required
language: bash
services:
- docker
script:
- sh build.sh

deploy:
 - provider: s3
   access_key_id: AKIAZHYMTJVVL6UKL6EC
   secret_access_key: $SECRET_ACCESS_KEY2
   bucket: bis.beast.se
   region: eu-north-1
   local-dir: target/site
   upload-dir: "git-action"
   acl: public_read
   skip_cleanup: true
   on:
    repo: BEAst-AB/beast-supply
    branch: main

 - provider: s3
   access_key_id: AKIAZHYMTJVVL6UKL6EC
   secret_access_key: $SECRET_ACCESS_KEY2
   bucket: bis.beast.se
   region: eu-north-1
   local-dir: target/site
   upload-dir: $TRAVIS_BRANCH
   acl: public_read
   skip_cleanup: true
   on:
    repo: BEAst-AB/beast-supply
    all_branches: true
    condition: $TRAVIS_BRANCH != 'main'
