[[benefits]]
= Benefits

PEPPOL BIS pre-award catalogue request will stimulate the service provider marked to develop services that cover tendering processes both for 
contracting authorities and economic operators. The Pre-award catalogue request will:

* make it possible for the CA to specify their procurement needs in form of a structured catalogue
* save time for the CA to have a standardized list of products and services
* save time for the CA to request a quote on non-standard products that are described by Properties or when Item numbers are unknown. 
* make it possible for the CA to use the pre-award catalogue request in mini-competitions and re-opening of competitions
* make it possible for economic operators to use the PEPPOL BIS pre-award catalogue xml when up-loading the tender in a 3-corner model on condition 
that tendering systems are compatible.
* save time for the EO not needing to manually enter the Request For Quote’s (RFQ’s) all information from a PDF or similar. Less risk of errors and 
misunderstandings.  
