= Version 4.0.5
[horizontal]
This release is based on:

* Peppol Post Award Community version 3.0.20 released Nov 2025.
* Peppol Logistics Community version 1.2 released in Dec 2025.

== Migration plan
*Publication*
The date is set to 2025-12-17. As of this date the release content is published. 
Stakeholders can start with implementing the changes.

*Mandatory use*
The date for the release content to become mandatory is set to 2026-03-16
As of this date the old version, May release 2025, is not allowed to be used anymore. 

[horizontal]
Changes to Peppol documentation below

To access the release notes for the Logistics and Post Award Community, please follow the links below:

* https://test-docs.peppol.eu/poacc/upgrade-3/2025-q4-mr/release-notes/[Peppol Post Award Community Release Notes,window=_blank]
* https://test-docs.peppol.eu/logistics/Release_1_2_Review/release-notes/[Peppol Logistics Community Release Notes,window=_blank]

== Changes to syntax
For changes in PoAC and LoC releases, please check release-notes for them.
Please check the change of engine type codes since this is not compatible with earlier versions.

== Changes to code lists and validation artefacts
For changes in PoAC and LoC releases, please check release-notes for them.

* Examples updated to handle new Swedish organization number validation (PEPPOL-COMMON-R049)