= Version 4.0.4
[horizontal]
This release is based on:

* Peppol Post Award Community version 3.0.14 released November 2024 and mandatory use is set to 2025-02-xx.
* Peppol Logistics Community version 1.1 with mandatory use 2025-02-xx.

== Migration plan
*Publication*
The date is set to 2024-12-xx. As of this date the release content is published. 
Stakeholders can start with implementing the changes.

*Mandatory use*
The date for the release content to become mandatory is set to 2025-02-xx
As of this date the old version, May release 2024, is not allowed to be used anymore. 

[horizontal]
Changes to Peppol documentation below

== BIS documentation
For changes in PoAC and LoC releases, please check release-notes for them.

* For BEAst 4.0.4. the Peppol BIS Catalogue with Response 3.1 and Peppol BIS Catalogue without Response 3.1 have been added. 
They were already before a part of the PoAC release.

== Changes to syntax
For changes in PoAC and LoC releases, please check release-notes for them.

* For BEAst 4.0.4. the Peppol Catalogue transaction 3.3 (T19) is added. It already before was a part of PoAC.

* Also Peppol Catalogue Response transaction 3.0 (T58) is added in release 4.0.4. It already before was a part of PoAC. 

== Changes to code lists and validation artefacts
For changes in PoAC and LoC releases, please check release-notes for them.

* Validation rules for Catalogue 3.3 (T19) and CatalogueResponse 3.0 (T58) have been added in release 4.0.4. They already existed in PoAC before.

