= Version 4.0.4
[horizontal]
This release is based on:

* Peppol Post Award Community version 3.0.14 released November 2024.
* Peppol Logistics Community version 1.1 released in December 2024.

== Migration plan
*Publication*
The date is set to 2024-01-08. As of this date the release content is published. 
Stakeholders can start with implementing the changes.

*Mandatory use*
The date for the release content to become mandatory is set to 2025-02-17
As of this date the old version, May release 2024, is not allowed to be used anymore. 

[horizontal]
Changes to Peppol documentation below

== BIS documentation
Please follow the links below to read the release notes for Logistics and Post Award Community.
* https://docs.peppol.eu/poacc/upgrade-3/2024-Q4/release-notes/[Peppol Post Award Community Release Notes]
* https://test-docs.peppol.eu/logistics/2024-Q4/release-notes/[Peppol Logistics Community Release Notes]

For BEAst 4.0.4. the Peppol BIS Catalogue with Response 3.1 and Peppol BIS Catalogue without Response 3.1 have been added. 
They were already before a part of the PoAC release.

== Changes to syntax
For changes in PoAC and LoC releases, please check release-notes for them.
Please check the change of engine type codes since this is not compatible with earlier versions.

* For BEAst 4.0.4. the Peppol Catalogue transaction 3.3 (T19) is added. It already before was a part of PoAC.

* Also Peppol Catalogue Response transaction 3.0 (T58) is added in release 4.0.4. It already before was a part of PoAC. 

* Added new commodity classification names for all documents with commodiy classification
** RF: Rentalföretagen 
** SB: Svensk Betong
** SBF: Svensk Beläggningsförening
** SW: Swedish Wood

== Changes to code lists and validation artefacts
For changes in PoAC and LoC releases, please check release-notes for them.

* Validation rules for Catalogue 3.3 (T19) and CatalogueResponse 3.0 (T58) have been added in release 4.0.4., the rules already existed in PoAC.
