= Version 4.0.5 --review
[horizontal]
This release is based on:

* Peppol Post Award Community version 3.0.19 released May 2025.
* Peppol Logistics Community version 1.1 released in December 2024.

== Migration plan
*Publication*
The date is set to 2025-07-01. As of this date the release content is published. 
Stakeholders can start with implementing the changes.

*Mandatory use*
The date for the release content to become mandatory is set to 2025-08-25
As of this date the old version, Nov release 2024, is not allowed to be used anymore. 

[horizontal]
Changes to Peppol documentation below

To access the release notes for the Logistics and Post Award Community, please follow the links below:

* https://docs.peppol.eu/poacc/upgrade-3/2025-Q2/release-notes/index.html[Peppol Post Award Community Release Notes,window=_blank]
* https://test-docs.peppol.eu/logistics/2024-Q4/release-notes/index.html[Peppol Logistics Community Release Notes,window=_blank]

== Changes to syntax
For changes in PoAC and LoC releases, please check release-notes for them.
Please check the change of engine type codes since this is not compatible with earlier versions.

== Changes to code lists and validation artefacts
For changes in PoAC and LoC releases, please check release-notes for them.

* Examples updated to handle new Swedish organization number validation (PEPPOL-COMMON-R049)