= Version 4.0.7
[horizontal]
This release is based on:

* Peppol Post Award Community version 3.0.21 released in May 2026.
* Peppol Logistics Community version 1.3 released in May 2026.

== Migration plan
*Publication*
The date is set to 2026-05-18. As of this date the release content is published. 
Stakeholders can start implementing the changes.

*Mandatory use*
The date for the release content to become mandatory is set to 2026-08-24
As of this date the old version, November release 2025, is not allowed to be used anymore. 

[horizontal]
Changes to Peppol documentation below

To access the release notes for the Logistics and Post Award Community, please follow the links below:

* https://docs.peppol.eu/poacc/upgrade-3/upcoming/release-notes/[Peppol Post Award Community Release Notes,window=_blank]
* https://docs.peppol.eu/logistics/2026-Q2/release-notes/[Peppol Logistics Community Release Notes,window=_blank]

== Changes to syntax
For changes in PoAC and LoC releases, please check release-notes for them.
Please check the change of engine type codes since this is not compatible with earlier versions.


== Changes to code lists and validation artefacts
For changes in PoAC and LoC releases, please check release-notes for them.

== Changes to documentation
For changes in PoAC and LoC releases, please check release-notes for them.

* Addition of reference to RB (retursystem byggpall) in documentation of ItemCLassificationCode
