[[item-properties]]
= Additional Item Properties

== Definition of a Property
In this document the term “property” is mentioned in several places. It is a way to describe the item when an item number is not known or it is not a 
standard product. 
The property can be identified by a NameCode that must be known by both sender and receiver, but better is to identify the property with an ID that 
is defined in a standard public Data Dictionary (DD) and to provide the attributes where to find the DD. 
It is recommended to use Property identification from standardised Data Dictionaries.   

== Use of Properties
Additional properties are meant for product properties that cannot be sent in any of the defined elements in PreAward Catalogue. Additional 
properties consist of the Name, NameCode and/or Identity of the property and the requested Value or Range. 

.Example of additional properties:
* Colour
* Nutrition +
Stated with amount per 100 g/ml.
* Genetically modified +
Legal values: True, False

.Example of use in the PreAward Catalogue request message
====
[source, xml, indent=0]
----
include::../../../../structure/snippets/ItemProperties.xml[tags=example1]
----

[source]
.Here an example of a Property that is defined with a Name-code in a codelist.
====

[source, xml, indent=0]
----
include::../../../../structure/snippets/ItemProperties.xml[tags=example2]
----

[source]
.And here an example of a Property defined by an ID in a DataTemplate with link.
====

[source, xml, indent=0]
----
include::../../../../structure/snippets/ItemProperties.xml[tags=example3]
----


