[[procurement-ref]]
= Reference to the Call for Tenders/Request for Quote (and Project identifier)

In B2G processes the pre-award catalogue shall refer to a previous call for tenders with pre-award catalogue request, often called 
the *procurement project identifier*. This Project identifier shall be provided in the element 
`cac:ReferencedContract/cac:ContractDocumentReference/cbc:ID` with `cac:ReferencedContract/cbc:ContractTypeCode` = 311. 
The reference to the Catalogue Request in cac:ReferencedContract/cbc:ID

When the referenced call for tenders has lots, the lot identifier shall be sent at line level in the element `cbc:ContractSubdivision`.

In B2B processes the same group and elements are used in a similar way. The reference to a preceding Catalogue Request (RFQ) is the same if one 
is received, but instead of having a “procurement project identifier”, a Project reference can be sent. If no RFQ is received, 
the cac:ContractDocumentReference/cbc:ID instead can contain a reference to a Framework Agreement or some other Contract between the parties. 
The cbc:ContractTypeCode should reflect that if that is the case. 

.Example on procurement project identifier
[source, xml, indent=0]
----
include::../snippets/Snippet-1.xml[tags=procurement]
----
<1>  Code 311 is mandatory
<2>  The procurement project identifier

.Lot identifier on line level
[source, xml, indent=0]
----
include::../../../../structure/snippets/Snippet_68.xml[tags=lot-ref]
...
----
